### ISSUE TITLE
Pulse without sound

### ISSUE THREAD

**Issue by Sle77en** [s-marley/ESP32-INMP441-Matrix-VU#1]
Hi,

I have pulses without a sound. So even with silence. I suspect that the microphone has a bug. What do you think?

Here you can take a look: https://www.dropbox.com/s/tudjnyesxygd2lo/telegram-cloud-document-2-5282922645820541774.mp4

**Comment by s-marley** [comment]
That definitely doens't look right. You could try adding a capacitor across the 3V3 and GND lines on the mic, see if there is some electrical interference that is being picked up, but these digital mics are normally pretty good at dealing with that anyway. I'm sure you've already checked that all of your connections are correct? Thats's a nice looking matrix by the way! Try running just  [this code](https://pastebin.com/Ua7s7LYF) without the LEDs, and see if you still pick up those jumps on the serial plotter output.

**Comment by Sle77en** [comment]
Hi :) Thanks for your fast answer! 
I am now one step closer to the solution. The malfunction only occurs when I operate the matrix with a power supply unit (5V / 10A). There is no disturbance when I operate it via USB via the ESP32. 
Do you have a tip for me?

**Comment by PaoloBassan** [comment]
hi, i'm trying to build your project but i can't find the <driver / i2s.h> library
can you help me please

**Comment by s-marley** [comment]
Sounds like it might be a cheap, noisy power supply! Try the capacitor thing I mentioned and see if that makes a difference. If not, you'll just have to use a higher quality supply unfortunately. Also make sure everything is well grounded as usual.

**Comment by Sle77en** [comment]
Yes it was a noisy power supply. Now i have a good one and all works finde :) Thank you very much!
