### ISSUE TITLE
hi, i'm trying to build your project but i can't find the <driver / i2s.h> library

### ISSUE THREAD

**Issue by PaoloBassan** [s-marley/ESP32-INMP441-Matrix-VU#2]
hi, i'm trying to build your project but i can't find the <driver / i2s.h> library
can you help me please

_Originally posted by @PaoloBassan in https://github.com/s-marley/ESP32-INMP441-Matrix-VU/issues/1#issuecomment-779302357_

**Comment by s-marley** [comment]
If you build it in the Arduino IDE and make sure an ESP32 board is selected as the target the library should be automatically available.

**Comment by PaoloBassan** [comment]
great, you helped me a lot and I learned how to solve this and other problems caused by my ignorance on the correct management of libraries and boards.
you are doing a great job :-))

**Comment by s-marley** [comment]
No worries, thank you!
