### ISSUE TITLE
LEDMatrix.h

### ISSUE THREAD

**Issue by pepster01** [s-marley/ESP32-INMP441-Matrix-VU#3]
Hi, 
I like this uv meter, you did a great job and I'm try to build one 8x8 for my self but I'm having problem compiling the code,
the error that comes up..  LEDMatrix.h: No such file or directory 
I have install all the libraries for this project but why it can't find the LEDMatix.h in the library.
Do you know where I'm going wrong with this, I really would appreciate the help.
Thanks 

Pepster

**Comment by s-marley** [comment]
LEDMatrix.h is from [here](https://github.com/AaronLiddiment/LEDMatrix). Make sure you have dowloaded this as a zip, then Sketch -> Include Library -> Add .ZIP library
If you've done that and it still doesn't work, I'm not sure what's going on for you I'm afraid!

**Comment by pepster01** [comment]
Hi,
I have resolved the problem by uninstall all the library and install just the library needed for the project.
Thanks

**Comment by s-marley** [comment]
Glad to know it' sorted.

**Comment by pepster01** [comment]
Can't wait to finished, soon I get the chance I buy you a coffee
