### ISSUE TITLE
Change intensivity of low frequences 

### ISSUE THREAD

**Issue by Sle77en** [s-marley/ESP32-INMP441-Matrix-VU#4]
Hey, i have another question :) 

Is it possible to reduce the intensivity of the first 5 frequency blocks of the 16x16 matrix? 
`    fftCalc[0] = (fftAdd(3,4)) /2;        // 60 - 100
    fftCalc[1] = (fftAdd(4,5)) /2;        // 80 - 120
    fftCalc[2] = (fftAdd(5,7)) /3;        // 100 - 160
    fftCalc[3] = (fftAdd(7,9)) /3;        // 140 - 200
    fftCalc[4] = (fftAdd(9,12)) /4;       // 180 - 260`

Because if you have bass-heavy music it will dominate the rest of the screen. 

If you can help me, i will buy you a coffee :D 

Best Regards!

**Comment by s-marley** [comment]
There is no simple fix that I'm aware of, but what you could do is adjust the values in
```
double fftResultPink[16] = {1.70,1.71,1.73,1.78,1.68,1.56,1.55,1.63,1.79,1.62,1.80,2.06,2.47,3.35,6.83,9.55};
```
This sets a multiplier for each band, so by adjusting them you can tailor the output to whatever you want it to look like. You'll have to have a play and see what happpens!

**Comment by Sle77en** [comment]
Hey :) Thank you very much. You will get your coffee ;D
