### ISSUE TITLE
The VU effects are really great. Would love to see them added to the sound reactive fork of wled.

### ISSUE THREAD

**Issue by tavdog** [s-marley/ESP32-INMP441-Matrix-VU#6]
I'm wondering how hard it would be put your vu visualizations into the sound reactive fork.  The 2d audio effects in the sound reactive forke pale in comparison to your hand coded VU code.  Also great job on the f3d file with the matrix size fully configurable.  I made an 8x32 sized base and everything works except for two little tabs.

**Comment by tavdog** [comment]
Nevermind.  I think it faster in a standalone configuration.  I'm building the 32x8 VU meter. It's gonna be siiiiiiick.

**Comment by s-marley** [comment]
I'd love to have this stuff incorporated into WLED, I don't know how to do it though as I've never written any patterns for it and it is very dependant on the aspect ratio of the matrix. It would need more work to make it more robust for arbitary matrix sizes / orientations / aspect ratios I would think. Not sure if these can be set in the WLED preferences? If @atuline want's to have a go, or knows someone who would like to try then I'd be happy to see it!

**Comment by atuline** [comment]
With our fork of WLED, we made a nice little wrapper that makes FastLED programming easier than ever. 

In having a quick look at the effects, the code is nice, short and self contained. We have some real nice orientation, panel, matrix and segment settings, but aspect ratios are a whole new ballgame. Might not hurt to have a look.
