### ISSUE TITLE
Glitchy led on 16x16 

### ISSUE THREAD

**Issue by tavdog** [s-marley/ESP32-INMP441-Matrix-VU#7]
I got my 16x16 together and it was behaving very strangely. very glitchy and unreadable during the ip address and very glitchy during the VU.  I tracked it down a missing delay line after FastLED.show();.   All of the ledmatrix examples have this and when I add delay(1); after all FastLED.show() lines the issue is fixed. will create a pull request.

**Comment by s-marley** [comment]
That's odd, I've never used a delay with a matrix and never had an issue.
Must be specific hardware. I flat out avoid delay in any form in my FastLED
code. I can add that line as an option, but I'll leave it commented out and
people can enable it if they need to. Thanks.

**Comment by tavdog** [comment]
ok.  it's just two lines in the code.  I thought it was my hardware at first too and even returned the matrix but the new one did the same thing so I don't know.
